on:
  pull_request:
    branches:
      - main
jobs:
  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ktlintCheck
        run: ./gradlew ktlintCheck
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run test
        run: ./gradlew test
  android:
    name: Compile Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run assembleDebug
        run: ./gradlew :client:androidApp:assembleDebug
  desktop:
    name: Compile Desktop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run assembleDebug
        run: ./gradlew :client:desktopApp:assemble
  js:
    name: Compile JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run browserWebpack
        run: ./gradlew :client:jsApp:jsBrowserWebpack
  ios:
    name: Compile iOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_12.5.app/Contents/Developer'
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run xcodebuild
        run: xcodebuild -workspace client/iosApp/iosApp.xcodeproj/project.xcworkspace/ -scheme iosApp -destination 'name=iPhone 11' build
